#!/bin/bash

uinstall () {
    name=$1
    check_command=$2
    install_command=$3

    # check for install
    echo "[ ] Checking for $name...  ($check_command)"
    if eval "$check_command &>/dev/null"; then
        echo "[+] $name already installed."
        return 0
    else
        echo "  [-] $name is not installed."
    fi

    # try to install
    echo "  [ ] Installing $name... ($install_command)"
    if eval "$install_command &>/dev/null"; then
        echo "  [+] Installing $name succeeded."
    else
        echo "  [!] Installing $name failed!"
        exit 1
    fi
}

# uinstall 'failtest' \
#     'failtest' \
#     'failtest'

# uinstall 'installtest' \
#     'installtest' \
#     'sleep 1'

# uinstall 'successtest' \
#     'sleep 1' \
#     ''

uinstall 'brew' \
    'brew --version' \
    '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'

uinstall 'brew-python2' \
    'which python2 | head -n 1 | grep /usr/local/bin/' \
    'brew install python2'

uinstall 'brew-python3' \
    'which python3 | head -n 1 | grep /usr/local/bin/' \
    'brew install python3'

uinstall 'pip2-virtualenv' \
    'pip2 freeze | grep "virtualenv"' \
    'pip2 install virtualenv'

uinstall 'pip3-virtualenv' \
    'pip3 freeze | grep "virtualenv"' \
    'pip3 install virtualenv'

uinstall 'pip3-vulture' \
    'pip3 freeze | grep "vulture"' \
    'pip3 install vulture'
